
/*  Â© Copyright CERN, 2015. All rights not expressly granted are reserved.
        
    The stub of this file was generated by Quasar (additional info: using transform designToDeviceHeader.xslt) 
    on 2020-06-24T17:07:21.537-04:00
    
    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.
    
    
    
 */





#ifndef __DAMAC__H__
#define __DAMAC__H__

#ifndef AMACv2_H_INCLUDE
#define AMACv2_H_INCLUDE

#include <vector>
#include <boost/thread/mutex.hpp>

#include <statuscode.h>
#include <uadatetime.h>
#include <session.h>


#include <DRoot.h>
#include <Configuration.hxx>

#include <Base_DAMAC.h>

#include <bitset>

using namespace std;

namespace Device
{
  
  class DAMAC:public Base_DAMAC
  {
    
  public:
    /* sample constructor */
    explicit DAMAC (const Configuration::AMAC & config,
  		    Parent_DAMAC * parent);

    //DAMAC(char *path);

    /* sample dtr */
    ~DAMAC ();
    
  private:
    /* Delete copy constructor and assignment operator */
    DAMAC (const DAMAC &);
    DAMAC & operator= (const DAMAC & other);


    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

  public:
    //register list for different purposes
    std::vector <int> ReadOnlyRegs1 = {10,11,12,13,14,15};
    std::vector <int> ReadOnlyRegs2 = {0,1,2,3,4,5,6,7,10,11,12,13,14,15,24,25,26,27,31};
    std::vector <int> WriteRegs = {32,33,34};
    std::vector <int> ReadWriteRegs = {40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,60,61,62,63,64,65,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,90,91,92,93,94,95,96,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171};
    

    void registers();
    float AMACv2_readIDET();  //for measuring the HV current from Ch 14
    int AMACv2_readAM(int AMACchan, int MUX);
    float AMACv2_readAM_calibrated(int AMACchan, int MUX);
    void AMACv2_zeroOffset(int AMACchan);

    void array_declaration();
  };
  
}
    
#endif // include guard
#endif // AMACv2_H_INCLUDE
      
