
/*  Â© Copyright CERN, 2015. All rights not expressly granted are reserved.
        
    The stub of this file was generated by Quasar (additional info: using transform designToDeviceHeader.xslt) 
    on 2020-06-24T17:07:21.537-04:00
    
    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.
    
    
    
 */





#ifndef __DAMAC__H__
#define __DAMAC__H__

#ifndef AMACv2_H_INCLUDE
#define AMACv2_H_INCLUDE

#include <vector>
#include <boost/thread/mutex.hpp>

#include <statuscode.h>
#include <uadatetime.h>
#include <session.h>


#include <DRoot.h>
#include <Configuration.hxx>

#include <Base_DAMAC.h>

#include <bitset>

using namespace std;

namespace Device
{
  
  class DAMAC:public Base_DAMAC
  {
    
  public:
    /* sample constructor */
    explicit DAMAC (const Configuration::AMAC & config,
  		    Parent_DAMAC * parent);
    
    //DAMAC(char *path);

    /* sample dtr */
    ~DAMAC ();
    
  private:
    /* Delete copy constructor and assignment operator */
    DAMAC (const DAMAC &);
    DAMAC & operator= (const DAMAC & other);
    
    
    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

  public:
    
    void registers();

    void array_declaration();

  private:
    //int channel = getParent()->busNumber();
    

  };
  
}
    
#endif // include guard
#endif // AMACv2_H_INCLUDE
      
